# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maple_utility.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapleUtility(object):
    def setupUi(self, MapleUtility):
        MapleUtility.setObjectName("MapleUtility")
        MapleUtility.resize(716, 651)
        self.mainWidget = QtWidgets.QWidget(MapleUtility)
        self.mainWidget.setGeometry(QtCore.QRect(4, 2, 711, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setMaximumSize(QtCore.QSize(130, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.entryList = QtWidgets.QListWidget(self.widget_2)
        self.entryList.setEnabled(True)
        self.entryList.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entryList.setFont(font)
        self.entryList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.entryList.setObjectName("entryList")
        self.verticalLayout.addWidget(self.entryList)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.editWidget = QtWidgets.QWidget(self.mainWidget)
        self.editWidget.setObjectName("editWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.editWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.editWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.subject = QtWidgets.QPlainTextEdit(self.editWidget)
        self.subject.setMinimumSize(QtCore.QSize(0, 47))
        self.subject.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.subject.setFont(font)
        self.subject.setObjectName("subject")
        self.verticalLayout_3.addWidget(self.subject)
        self.label_2 = QtWidgets.QLabel(self.editWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pronFrame = QtWidgets.QFrame(self.editWidget)
        self.pronFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pronFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pronFrame.setObjectName("pronFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pronFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pronSamantha = QtWidgets.QRadioButton(self.pronFrame)
        self.pronSamantha.setObjectName("pronSamantha")
        self.horizontalLayout.addWidget(self.pronSamantha)
        self.pronDaniel = QtWidgets.QRadioButton(self.pronFrame)
        self.pronDaniel.setObjectName("pronDaniel")
        self.horizontalLayout.addWidget(self.pronDaniel)
        self.verticalLayout_3.addWidget(self.pronFrame)
        self.label_3 = QtWidgets.QLabel(self.editWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.paraphrase = QtWidgets.QTextEdit(self.editWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.paraphrase.setFont(font)
        self.paraphrase.setObjectName("paraphrase")
        self.verticalLayout_3.addWidget(self.paraphrase)
        self.label_4 = QtWidgets.QLabel(self.editWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.extension = QtWidgets.QPlainTextEdit(self.editWidget)
        self.extension.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.extension.setFont(font)
        self.extension.setObjectName("extension")
        self.verticalLayout_3.addWidget(self.extension)
        self.label_5 = QtWidgets.QLabel(self.editWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.example = QtWidgets.QTextEdit(self.editWidget)
        self.example.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.example.setFont(font)
        self.example.setObjectName("example")
        self.verticalLayout_3.addWidget(self.example)
        self.source = QtWidgets.QTextEdit(self.editWidget)
        self.source.setMinimumSize(QtCore.QSize(0, 22))
        self.source.setMaximumSize(QtCore.QSize(16777215, 22))
        self.source.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.source.setReadOnly(True)
        self.source.setObjectName("source")
        self.verticalLayout_3.addWidget(self.source)
        self.label_6 = QtWidgets.QLabel(self.editWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.hint = QtWidgets.QPlainTextEdit(self.editWidget)
        self.hint.setMinimumSize(QtCore.QSize(0, 23))
        self.hint.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint.setFont(font)
        self.hint.setObjectName("hint")
        self.verticalLayout_3.addWidget(self.hint)
        self.widget = QtWidgets.QWidget(self.editWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveAllButton = QtWidgets.QPushButton(self.widget)
        self.saveAllButton.setObjectName("saveAllButton")
        self.horizontalLayout_2.addWidget(self.saveAllButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.discardButton = QtWidgets.QPushButton(self.widget)
        self.discardButton.setObjectName("discardButton")
        self.horizontalLayout_2.addWidget(self.discardButton)
        self.nextButton = QtWidgets.QPushButton(self.widget)
        self.nextButton.setAcceptDrops(True)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.editWidget)

        self.retranslateUi(MapleUtility)
        QtCore.QMetaObject.connectSlotsByName(MapleUtility)

    def retranslateUi(self, MapleUtility):
        _translate = QtCore.QCoreApplication.translate
        MapleUtility.setWindowTitle(_translate("MapleUtility", "Maple Utility"))
        self.label_7.setText(_translate("MapleUtility", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Stay Hungry</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Stay Foolish</span></p></body></html>"))
        self.label.setText(_translate("MapleUtility", "Subject"))
        self.subject.setPlainText(_translate("MapleUtility", "Subject"))
        self.label_2.setText(_translate("MapleUtility", "Pronunciation"))
        self.pronSamantha.setText(_translate("MapleUtility", "Samantha"))
        self.pronDaniel.setText(_translate("MapleUtility", "Daniel"))
        self.label_3.setText(_translate("MapleUtility", "Paraphrase"))
        self.paraphrase.setHtml(_translate("MapleUtility", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Paraphrase</p></body></html>"))
        self.label_4.setText(_translate("MapleUtility", "Extension"))
        self.extension.setPlainText(_translate("MapleUtility", "Extension\n"
""))
        self.label_5.setText(_translate("MapleUtility", "Example"))
        self.example.setHtml(_translate("MapleUtility", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example</p></body></html>"))
        self.source.setHtml(_translate("MapleUtility", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Source</span></p></body></html>"))
        self.label_6.setText(_translate("MapleUtility", "Hint"))
        self.hint.setPlainText(_translate("MapleUtility", "Hint"))
        self.saveAllButton.setText(_translate("MapleUtility", "Save All"))
        self.discardButton.setText(_translate("MapleUtility", "Discard"))
        self.nextButton.setText(_translate("MapleUtility", "Confirm"))

