on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-14]
        include:
          - os: macos-12
            label: intel
          - os: macos-14
            label: arm64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    
    - name: Install lame and create-dmg
      run: |
        brew update
        brew install lame create-dmg
   
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --windowed -noconsole --add-binary="$(which lame):." -n "Maple Vocab Utility" --icon resource/icon.icns maple_vocab_utility.py

    - name: Create dmg
      run: |
        chmod +x ./create_dmg.sh
        ./create_dmg.sh ${{ github.ref_name }} ${{ matrix.label }}
      shell: bash
    
    - uses: actions/upload-artifact@v3
      with:
        path: maple-utility-${{ github.ref_name }}-macos-${{ matrix.label }}.dmg
