on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install lame
      run: |
        brew update
        brew install lame
   
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --windowed -noconsole --add-binary="$(where lame):." -n "Maple Vocab Utility" --icon resource/icon.icns maple_vocab_utility.py
    
    - uses: actions/upload-artifact@v2
      with:
        path: 'dist/Maple Vocab Utility.app'
