on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install lame and create-dmg
      run: |
        brew update
        brew install lame create-dmg
   
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --windowed -noconsole --add-binary="$(which lame):." -n "Maple Vocab Utility" --icon resource/icon.icns maple_vocab_utility.py

    - name: Create dmg
      run: |
        chmod +x ./create_dmg.sh
        ./create_dmg.sh
      shell: bash
    
    - uses: actions/upload-artifact@v2
      with:
        path: 'Maple-Vocab-Utility-Installer.dmg'
